my_dbt:
  
  # Default target, can switch this in the command line via locally or dbt cloud: dbt run --target staging_wh
  target: prod_wh

  outputs:
    prod_wh:
      type: snowflake
      account: "{{ env_var('SNOWF_ACCOUNT') }}"
      user: "{{ env_var('SNOWF_USER') }}"
      password: "{{ env_var('SNOWF_PASSWORD') }}"
      role: "{{ env_var('SNOWF_ROLE') }}"
      database: "{{ env_var('SNOWF_DATABASE') }}"
      warehouse: production_wh
      schema: "{{ env_var('SNOWF_SCHEMA') }}"
      threads: 1
      client_session_keep_alive: False

    staging_wh:
      type: snowflake
      account: "{{ env_var('SNOWF_ACCOUNT') }}"
      user: "{{ env_var('SNOWF_USER') }}"
      password: "{{ env_var('SNOWF_PASSWORD') }}"
      role: "{{ env_var('SNOWF_ROLE') }}"
      database: "{{ env_var('SNOWF_DATABASE') }}"
      warehouse: staging_wh
      schema: "{{ env_var('SNOWF_SCHEMA') }}"
      threads: 1
      client_session_keep_alive: False
