{{ config(
    materialized="view"
) }}

select 
    ASSIST_PERCENTAGE
    ,ASSIST_RATIO
    ,ASSIST_TO_TURNOVER
    ,DEFENSIVE_RATING
    ,DEFENSIVE_REBOUND_PERCENTAGE
    ,EFFECTIVE_FIELD_GOAL_PERCENTAGE
    ,ESTIMATED_DEFENSIVE_RATING
    ,ESTIMATED_NET_RATING
    ,ESTIMATEDOFFENSIVERATING
    ,ESTIMATED_PACE
    ,ESTIMATED_TEAM_TURNOVER_PERCENTAGE
    ,ESTIMATED_USAGE_PERCENTAGE
    ,GAME_ID
    ,MINUTES
    ,NET_RATING
    ,OFFENSIVE_RATING
    ,OFFENSIVE_REBOUND_PERCENTAGE
    ,PACE
    ,PACE_PER40
    ,PIE
    ,POSSESSIONS
    ,REBOUND_PERCENTAGE
    ,TEAM_CITY
    ,TEAM_ID
    ,TEAM_NAME
    ,TEAM_SLUG
    ,TEAM_TRICODE
    ,TRUE_SHOOTING_PERCENTAGE
    ,TURN_OVER_RATIO
    ,USAGE_PERCENTAGE
from {{source('raw', 'team_boxscore')}}