{{ config(
    materialized="view"
) }}

select 
    ASSISTPERCENTAGE as ASSIST_PERCENTAGE
    ,ASSISTRATIO as ASSIST_RATIO
    ,ASSISTTOTURNOVER as ASSIST_TO_TURNOVER
    ,DEFENSIVERATING as DEFENSIVE_RATING
    ,DEFENSIVEREBOUNDPERCENTAGE as DEFENSIVE_REBOUND_PERCENTAGE
    ,EFFECTIVEFIELDGOALPERCENTAGE as EFFECTIVE_FIELD_GOAL_PERCENTAGE
    ,ESTIMATEDDEFENSIVERATING as ESTIMATED_DEFENSIVE_RATING
    ,ESTIMATEDNETRATING as ESTIMATED_NET_RATING
    ,ESTIMATEDOFFENSIVERATING as ESTIMATED_OFFENSIVE_RATING
    ,ESTIMATEDPACE as ESTIMATED_PACE
    ,ESTIMATEDTEAMTURNOVERPERCENTAGE as ESTIMATED_TEAM_TURNOVER_PERCENTAGE
    ,ESTIMATEDUSAGEPERCENTAGE as ESTIMATED_USAGE_PERCENTAGE
    ,GAMEID as GAME_ID
    ,MINUTES as MINUTES
    ,NETRATING as NET_RATING
    ,OFFENSIVERATING as OFFENSIVE_RATING
    ,OFFENSIVEREBOUNDPERCENTAGE as OFFENSIVE_REBOUND_PERCENTAGE
    ,PACE as PACE
    ,PACEPER40 as PACE_PER40
    ,PIE as PIE
    ,POSSESSIONS as POSSESSIONS
    ,REBOUNDPERCENTAGE as REBOUND_PERCENTAGE
    ,TEAMCITY as TEAM_CITY
    ,TEAMID as TEAM_ID
    ,TEAMNAME as TEAM_NAME
    ,TEAMSLUG as TEAM_SLUG
    ,TEAMTRICODE as TEAM_TRICODE
    ,TRUESHOOTINGPERCENTAGE as TRUE_SHOOTING_PERCENTAGE
    ,TURNOVERRATIO as TURN_OVER_RATIO
    ,USAGEPERCENTAGE as USAGE_PERCENTAGE
from {{source('raw', 'team_boxscore')}}